#!/usr/bin/env node
// tools/parse-sauce.js
//
// Parses a .txt recipe file (see FORMAT.md) into a sauce module and
// registers it in data/data.json (category/subcategory tree) and
// data/keys.json (ALL_SAUCE_KEYS).
//
// Usage:
//   node tools/parse-sauce.js <recipe.txt> [--project-root <path>] [--dry-run]
//
// <path>/data/data.json, <path>/data/keys.json, <path>/data/sauces/ are
// read and updated in place. Defaults to the current directory's ../.

const fs = require('fs');
const path = require('path');

const CLASS_MAP = { Ro: 'Robuchon', Es: 'Escoffier', Bo: 'Bocuse' };

function _slug(name) {
  return String(name)
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[\s-]+/g, '_')
    .replace(/[^a-z0-9_]/g, '');
}

function splitList(s) {
  return s.split(',').map(x => x.trim()).filter(Boolean);
}

function parseIngredientBlock(lines) {
  // lines like: "[base] egg yolks (5); clarified butter (250g)"
  const out = {};
  for (const line of lines) {
    const m = line.match(/^\[([^\]]+)\]\s*(.*)$/);
    if (!m) throw new Error('Bad INGREDIENTS line (expected "[tag] item; item"): ' + line);
    const tag = m[1].trim();
    const items = m[2].split(';').map(x => x.trim()).filter(Boolean);
    out[tag] = items;
  }
  return out;
}

function parseStepsBlock(lines) {
  // "1. text" -> strip leading "N." / "N)" numbering
  return lines.map(l => l.replace(/^\s*\d+[.)]\s*/, '').trim()).filter(Boolean);
}

function parseTxt(raw) {
  const ukSplit = raw.split(/\n---\s*UK\s*---\n/i);
  const enText = ukSplit[0];
  const ukText = ukSplit[1] || '';

  function parseSection(text) {
    const lines = text.split('\n');
    const fields = {};
    let i = 0;
    while (i < lines.length) {
      const line = lines[i];
      const trimmed = line.trim();
      if (!trimmed) { i++; continue; }

      const kv = trimmed.match(/^([A-Z_]+):\s*(.*)$/);
      if (!kv) { i++; continue; }
      const key = kv[1];
      const rest = kv[2];

      if (['INGREDIENTS', 'INGREDIENTS_UK'].includes(key)) {
        const block = [];
        i++;
        while (i < lines.length && lines[i].trim() && !lines[i].trim().match(/^[A-Z_]+:/)) {
          block.push(lines[i].trim());
          i++;
        }
        fields[key] = parseIngredientBlock(block);
        continue;
      }
      if (['STEPS', 'STEPS_UK'].includes(key)) {
        const block = [];
        i++;
        while (i < lines.length && lines[i].trim() && !lines[i].trim().match(/^[A-Z_]+:/)) {
          block.push(lines[i].trim());
          i++;
        }
        fields[key] = parseStepsBlock(block);
        continue;
      }
      if (['RECIPE', 'RECIPE_UK'].includes(key)) {
        const block = rest ? [rest] : [];
        i++;
        while (i < lines.length && lines[i].trim() && !lines[i].trim().match(/^[A-Z_]+:/)) {
          block.push(lines[i].trim());
          i++;
        }
        fields[key] = block.join(' ').trim();
        continue;
      }

      // simple single-line field
      fields[key] = rest.trim();
      i++;
    }
    return fields;
  }

  const en = parseSection(enText);
  const uk = parseSection(ukText);
  return { en, uk };
}

function buildSauceObject(en, uk) {
  const cls = en.CLASS;
  if (!CLASS_MAP[cls]) throw new Error('CLASS must be one of Ro/Es/Bo, got: ' + cls);
  const key = `${en.NAME} (${cls})`;

  const obj = {
    nm: key,
    pr: en.PAIRS_WITH ? splitList(en.PAIRS_WITH) : [],
    ig: en.INGREDIENTS || {},
    st: en.STEPS || [],
    rc: en.RECIPE || '',

    nm_uk: uk.NAME_UK || '',
    pr_uk: uk.PAIRS_WITH_UK ? splitList(uk.PAIRS_WITH_UK) : [],
    ig_uk: uk.INGREDIENTS_UK || {},
    st_uk: uk.STEPS_UK || [],
    rc_uk: uk.RECIPE_UK || '',

    fr: en.FR || '',
    cat: en.CATEGORY,
    mo: en.MOTHER || '',
    tp: en.TYPE || '',
    tm: en.TEMP || '',
    bs: en.BASE || '',
    df: en.DIFFICULTY || '',
    ti: en.TIME || '',
    dv: en.DERIVATIVES ? splitList(en.DERIVATIVES) : [],
    sm: en.SIMILAR ? splitList(en.SIMILAR) : [],
    cl: CLASS_MAP[cls],
    photo: en.PHOTO ? `./image/${en.PHOTO}` : ''
  };
  if (uk.BASE_UK) obj.bs_uk = uk.BASE_UK;
  if (uk.TIME_UK) obj.ti_uk = uk.TIME_UK;

  return { key, obj, subcategory: en.SUBCATEGORY };
}

function serializeModule(key, obj) {
  // Preserve field order matching the project's existing sauce files.
  const order = ['nm','pr','ig','st','rc','nm_uk','pr_uk','ig_uk','st_uk','rc_uk',
                  'fr','cat','mo','tp','tm','bs','bs_uk','df','ti','ti_uk','dv','sm','cl','photo'];
  const ordered = {};
  for (const k of order) if (obj[k] !== undefined) ordered[k] = obj[k];

  const body = JSON.stringify(ordered, null, 2)
    .replace(/^\{/, '{')
    .replace(/^/, '  ');

  return `// data/sauces/${_slug(key)}.js\n` +
    `// Auto-generated by tools/parse-sauce.js from a .txt recipe source.\n\n` +
    `export default {\n  "${key}": ${body.trim().slice(1, -1).trim() ? body : '{}'}\n};\n`;
}

// Simpler, safer serializer: build the object literal by hand so keys are
// unquoted where valid, matching existing file style closely enough,
// and multi-line strings/arrays stay readable.
function jsLiteral(val, indent) {
  const pad = '  '.repeat(indent);
  const padIn = '  '.repeat(indent + 1);
  if (Array.isArray(val)) {
    if (val.length === 0) return '[]';
    return '[' + val.map(v => JSON.stringify(v)).join(', ') + ']';
  }
  if (val && typeof val === 'object') {
    const keys = Object.keys(val);
    if (keys.length === 0) return '{}';
    const lines = keys.map(k => `${padIn}${k}: ${jsLiteral(val[k], indent + 1)}`);
    return '{\n' + lines.join(',\n') + '\n' + pad + '}';
  }
  return JSON.stringify(val);
}

function serializeSauceFile(key, obj) {
  const order = ['nm','pr','ig','st','rc','nm_uk','pr_uk','ig_uk','st_uk','rc_uk',
                  'fr','cat','mo','tp','tm','bs','bs_uk','df','ti','ti_uk','dv','sm','cl','photo'];
  const lines = [];
  for (const k of order) {
    if (obj[k] === undefined) continue;
    lines.push(`    ${k}: ${jsLiteral(obj[k], 2)}`);
  }
  return `// data/sauces/${_slug(key)}.js\n` +
    `// Auto-generated by tools/parse-sauce.js from a .txt recipe source.\n\n` +
    `export default {\n  "${key}": {\n${lines.join(',\n')}\n  }\n};\n`;
}

function main() {
  const args = process.argv.slice(2);
  const txtPath = args[0];
  if (!txtPath) {
    console.error('Usage: node parse-sauce.js <recipe.txt> [--project-root <path>] [--dry-run]');
    process.exit(1);
  }
  const rootIdx = args.indexOf('--project-root');
  const projectRoot = rootIdx >= 0 ? args[rootIdx + 1] : path.resolve(__dirname, '..');
  const dryRun = args.includes('--dry-run');

  const raw = fs.readFileSync(txtPath, 'utf8');
  const { en, uk } = parseTxt(raw);

  if (!en.NAME) throw new Error('Missing NAME field');
  if (!en.CATEGORY) throw new Error('Missing CATEGORY field');
  if (!en.SUBCATEGORY) throw new Error('Missing SUBCATEGORY field');

  const { key, obj, subcategory } = buildSauceObject(en, uk);
  const slug = _slug(key);
  const sauceFilePath = path.join(projectRoot, 'data', 'sauces', `${slug}.js`);
  const dataJsonPath = path.join(projectRoot, 'data', 'data.json');
  const keysJsonPath = path.join(projectRoot, 'data', 'keys.json');

  if (fs.existsSync(sauceFilePath)) {
    throw new Error(`Sauce file already exists: ${sauceFilePath} — refusing to overwrite`);
  }

  const dataJson = JSON.parse(fs.readFileSync(dataJsonPath, 'utf8'));
  const cat = dataJson.cats.find(c => c.nm === en.CATEGORY);
  if (!cat) throw new Error(`Category not found in data.json: "${en.CATEGORY}"`);
  const sub = cat.subs.find(s => s.nm === subcategory);
  if (!sub) throw new Error(`Subcategory not found in category "${en.CATEGORY}": "${subcategory}"`);

  if (sub.s.includes(key)) {
    throw new Error(`Sauce "${key}" already listed in ${en.CATEGORY} / ${subcategory}`);
  }

  const keysJson = JSON.parse(fs.readFileSync(keysJsonPath, 'utf8'));
  if (keysJson.includes(key)) {
    throw new Error(`Sauce "${key}" already present in keys.json`);
  }

  const fileContent = serializeSauceFile(key, obj);

  // Validate the generated module actually parses and has the right shape
  const tmpCheck = path.join('/tmp', `_check_${slug}_${Date.now()}.mjs`);
  fs.writeFileSync(tmpCheck, fileContent.replace(/^\/\/.*\n/gm, '') , 'utf8');

  console.log('--- Parsed sauce ---');
  console.log('Key:        ', key);
  console.log('Slug/file:  ', `data/sauces/${slug}.js`);
  console.log('Category:   ', en.CATEGORY, '/', subcategory);
  console.log('Ingredients tags:', Object.keys(obj.ig).join(', ') || '(none)');
  console.log('Steps:      ', obj.st.length);
  console.log('Derivatives:', obj.dv.join(', ') || '(none)');
  console.log('Similar:    ', obj.sm.join(', ') || '(none)');

  if (dryRun) {
    console.log('\n--dry-run: no files written.\n');
    console.log(fileContent);
    return;
  }

  fs.writeFileSync(sauceFilePath, fileContent, 'utf8');

  sub.s.push(key);
  sub.s_uk = sub.s_uk || [];
  sub.s_uk.push(uk.NAME_UK || '');
  fs.writeFileSync(dataJsonPath, JSON.stringify(dataJson, null, 2), 'utf8');

  keysJson.push(key);
  keysJson.sort((a, b) => a.localeCompare(b, ['uk', 'en'], { sensitivity: 'base' }));
  fs.writeFileSync(keysJsonPath, JSON.stringify(keysJson, null, 2), 'utf8');

  console.log('\nWritten:');
  console.log(' -', sauceFilePath);
  console.log(' -', dataJsonPath, '(added to', en.CATEGORY, '/', subcategory + ')');
  console.log(' -', keysJsonPath);
}

main();
